### ISSUE TITLE
Should error when `--dump` is passed and no necessist.db is found

### ISSUE THREAD

**Issue by smoelius** [trailofbits/necessist#119]
What I imagine is that somehow, the arguments to this function are reworked, and a check is added involving the `dump` flag: https://github.com/trailofbits/necessist/blob/7cdeac500dbb3d04879734f85c983e57e1482685/core/src/sqlite.rs#L64-L68

Here is where `sqlite::init` is called (you can see the `dump` flag is already incorporated into the `must_not_exist` argument):
https://github.com/trailofbits/necessist/blob/7cdeac500dbb3d04879734f85c983e57e1482685/core/src/core.rs#L175-L179

Ideally, the fix would also include a [`trycmd`](https://crates.io/crates/trycmd) test to verify the new behavior. That would involve adding a test to this directory: https://github.com/trailofbits/necessist/tree/master/core/tests/necessist_db_absent

**Comment by PatStiles** [comment]
Interested in this!

**Comment by smoelius** [comment]
I'd love to have some help with this.

What I imagine is that somehow, the arguments to this function are reworked, and a check is added involving the `dump` flag: https://github.com/trailofbits/necessist/blob/7cdeac500dbb3d04879734f85c983e57e1482685/core/src/sqlite.rs#L64-L68

Here is where `sqlite::init` is called (you can see the `dump` flag is already incorporated into the `must_not_exist` argument):
https://github.com/trailofbits/necessist/blob/7cdeac500dbb3d04879734f85c983e57e1482685/core/src/core.rs#L175-L179

Ideally, the fix would also include a [`trycmd`](https://crates.io/crates/trycmd) test to verify the new behavior. That would involve adding a test to this directory: https://github.com/trailofbits/necessist/tree/master/core/tests/necessist_db_absent
