### ISSUE TITLE
Improvements in foundry support

### ISSUE THREAD

**Issue by tarunbhm** [trailofbits/necessist#265]
In this issue we list the improvements that can be made to the foundry support:

1. Do not remove `.expectCall` lines in mutations
2. Do not remove `.log` lines in mutations

**Comment by smoelius** [comment]
I think these are good ideas.

**Comment by 0xPhaze** [comment]
Additional thought:
- not all `vm.` calls should be filtered out (if a test still passes when removing `vm.roll`, `vm.prank`, ... it could be worrisome)
