### ISSUE TITLE
Check if package.json exists while installing node modules

### ISSUE THREAD

**Issue by tarunbhm** [trailofbits/necessist#532]
The `install_node_modules` function does not check if the `package.json` file exists in the project directory. This function is used for foundry projects as well to support foundry projects with hardhat dependencies. But dry run fails for the pure foundry projects because they don't have a `package.json` file.

https://github.com/trailofbits/necessist/blob/b8ac93c8789cba24d75864feb0c0dd140c94175f/frameworks/src/ts_utils.rs#L6-L27

Adding a check if the `package.json` file exists will resolve this issue.

**Comment by smoelius** [comment]
Fixed by #580
